### ISSUE TITLE
Cannot replace image within textual as widget

### ISSUE THREAD

**Issue by SusannaMaria** [lnqs/textual-image#43]
I really like this component and would like to use it in a music database to display covers. Unfortunately I have the problem that I can not update it within a textual application as a widget with other image data, it flickers but does not display the new image but only the old image is displayed.

```
        image_path = "/mnt/c/temp/cover.jpg"
        image_bin = PIL.Image.open(image_path)
        image_widget = self.query_one("#image_widget")
        image_widget.image = image_bin
        image_widget.render()
```

I have tried several options and unfortunately I can't get any further. Perhaps you can show me an example of how I can replace an image within a textual app in an image widget?

Edit: It is related to tgp and sixel but refresh works with halfcell

**Comment by lnqs** [comment]
Hey, thanks a lot for the report!
I'm quite busy currently as I'm moving to a new flat, but I'll have a look at this issues as soon as possible.

**Comment by basnijholt** [comment]
I am glad I found this issue because I was running into the exact same problem thinking I did something wrong 😅

@SusannaMaria, I worked around this issue by using a `Container` and simply recreating the `Image` each time, see this commit: https://github.com/basnijholt/tuitorial/commit/9a6e6155c16940bcd28d20a6ce2e31450880deab.

Also using this as an opportunity to thank you @lnqs for creating this tool!

**Comment by SusannaMaria** [comment]
@basnijholt thank you very much for providing a workaround! And of course @lnqs for this overall great widget

**Comment by lnqs** [comment]
Release 0.7.0 should fix the issue. Can you confirm if it works for you?

**Comment by basnijholt** [comment]
@lnqs, that works! Thanks a lot, I already simplified the code in https://github.com/basnijholt/tuitorial/pull/16.

**Comment by lyovushka** [comment]
I still see this issue, but only in terminals with TGP (kitty and ghostty). It works fine with sixels (foot). Here is an example code to reproduce the issue

``` python
from textual.app import App, ComposeResult
from textual.widgets import Checkbox
from textual_image.widget import Image
import pandas as pd
import numpy as np
import PIL.Image
import io

df = pd.DataFrame({"a": np.random.normal(size=100)})


class ImageApp(App[None]):
    def __init__(self):
        super().__init__()
        self.image = Image()
        b = io.BytesIO()
        df.plot().figure.savefig(b)
        b.seek(0)
        self.image.image = PIL.Image.open(b)
        self.grid = Checkbox("grid")

    def on_checkbox_changed(self):
        b = io.BytesIO()
        df.plot(**{"grid": self.grid.value}).figure.savefig(b)
        b.seek(0)
        self.image.image = PIL.Image.open(b)

    def compose(self) -> ComposeResult:
        yield self.grid
        yield self.image


ImageApp().run()
```

Clicking on the checkbox will enable/disable the grid in the background. This often doesn't change the image unless I double click on the image (though sometimes the change in the image works).

**Comment by lnqs** [comment]
Thanks for the report, I can reproduce the issue. I'll have a look into it soon.

**Comment by lnqs** [comment]
Should be fixed with version 0.8.1
